# https://pre-commit.com
exclude: "examples|reports"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: debug-statements #Check for debugger imports and breakpoint() in python files
      - id: check-ast #Simply check whether files parse as valid python
      - id: fix-byte-order-marker #removes UTF-8 byte order marker
      - id: check-json
      - id: detect-private-key # detect-private-key is not in repo
      - id: check-yaml
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
      - id: check-case-conflict #Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT
      - id: end-of-file-fixer #Makes sure files end in a newline and only a newline
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args: ['--pattern', 'TODO|todo|fixme|FIXME']
        stages: [pre-push]
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check
        language: python
        args: [--fix, --exit-non-zero-on-fix, --line-length=79]
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: python
        args: [--line-length=79]
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs #blacken-docs is a pre-commit hook that runs to check for issues in the docs
        additional_dependencies: [black]
  - repo: local
    hooks:
      - id: mypy # mypy is a pre-commit hook that runs as a linter to check for type errors
        name: mypy
        entry: mypy
        language: system
        types: [python]
        stages:
          - "pre-push"
          - "pre-merge-commit"
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        language: system
        types: [python]
        entry: pytest
        pass_filenames: false
        always_run: true
        args: [--doctest-modules]
        stages: [pre-push]
  - repo: https://github.com/roy-ht/pre-commit-jupyter
    rev: v1.2.1
    hooks:
      - id: jupyter-notebook-cleanup
        args:
          - --remove-kernel-metadata
          - --pin-patterns
          - "[pin];[donotremove]"
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.4.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [pre-push]
