services:
  pydev:
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ..:/workspace
    ports:
      - "8888:8888"
    environment:
      - PATH=/home/vscode/.cargo/bin:$PATH
    command: sleep infinity